### ISSUE TITLE
Suggestion: Adding Custom Focuses to items

### ISSUE THREAD

**Issue by Lyinggod** [superseva/ac2d20#6]
The ability to add focuses to items. The character sheet has this already but this but the ability does not appear to exist to add these to an item, weapon, etc. Example might be adding "Throwing" for grenades, spears, rocks, etc.

**Comment by superseva** [comment]
There is no simple way of me doing this right now.
I need to see how to implement this and not rewrite much since I don't have time atm.
If nothing else I might introduce custom focus text input on the item sheet in the next update.

**Comment by superseva** [comment]
All of this is now done by making your own skill compendium and then, in the settings, telling the system to use it instead of the default one
for example:
1. make a compendium for items
2. add custom skills to it
3. go to settings and change `ac2d20.skills` to the compendium you want. If it is a compendium made in that world use `world.my-compendium-name`
