### ISSUE TITLE
Custom Skill Focuses to weapon rolls

### ISSUE THREAD

**Issue by NinjaPirateBob** [superseva/ac2d20#9]
I'm adding the Vehicle Weapons focus to fighting and it would be nice to be able to select it from the drop-down menu under the weapon's details when creating a weapon to put on a vehicle sheet in some way.

**Comment by superseva** [comment]
All of this is now done by making your own skill compendium and then, in the settings, telling the system to use it instead of the default one
for example:
1. make a compendium for items
2. add custom skills to it
3. go to settings and change `ac2d20.skills` to the compendium you want. If it is a compendium made in that world use `world.my-compendium-name`
